src/core-bank/core-bank.service.ts
src/cron-jobs/cron-jobs.module.ts
src/database/seeds/status/status-seed.service.ts
src/mail-count/mail-count.service.spec.ts
src/mail-count/mail-count.service.ts
src/settings/settings.controller.ts
src/settings/settings.service.ts
src/ticket-revenues/ticket-revenues.service.ts
src/users/users.service.ts
src/utils/enums/http-error-messages.enum.ts
src/utils/pipes/validate-enum.pipe.ts
src/utils/validators/is-matching-type.validator.ts

O merge anterior quebrou a API, provavelmente o pod estava executando um snapshot anterior.

fix: conflict errors braking api

---

src/auth/auth.service.ts
src/mail-history/entities/mail-history.entity.ts
src/mail-history/mail-history.service.ts
src/users/dto/update-user.dto.ts
src/users/users.service.ts

> Testes manuais apenas. Para poupar tempo não foram feitos testes unitário.
Se novo email existe em outro usuário
- Lança erro
Se novo email é novo no sistema
- Atualiza usuário
- Atualiza histórico de email com status = na fila
Se novo email é igual ao antigo; com ou sem demais dados
- Atualiza normalmente
Se inseriu nova senha
- Atualiza senha
- Ao logar permissionário com nova senha, deve retornar sucesso

Corrigir lógica na atualização do usuário

---

README.md
src/bank-statements/bank-statements.service.ts
src/bank-statements/interfaces/bank-statements-response.interface.ts
src/database/seeds/mail-history/mail-history-seed-data.service.ts
src/database/seeds/mail-history/mail-history-seed.module.ts
src/database/seeds/mail-history/mail-history-seed.service.ts
src/database/seeds/run-seed.ts
src/database/seeds/seed.module.ts
src/database/seeds/user/user-seed-data.service.ts
src/database/seeds/user/user-seed.module.ts
src/database/seeds/user/user-seed.service.ts
src/jae/data/jae-data.service.spec.ts
src/jae/data/jae-data.service.ts
src/mail-history/interfaces/mail-history-data.interface.ts
src/ticket-revenues/interfaces/ticket-revenues-group.interface.ts
src/ticket-revenues/interfaces/ticket-revenues-grouped-response.interface.ts
src/ticket-revenues/interfaces/tr-count-content.interface.ts
src/ticket-revenues/objs/TicketRevenuesGroup.ts
src/ticket-revenues/ticket-revenues.controller.spec.ts
src/ticket-revenues/ticket-revenues.controller.ts
src/ticket-revenues/ticket-revenues.service.spec.ts
src/ticket-revenues/ticket-revenues.service.ts
src/ticket-revenues/utils/ticket-revenues-groups.utils.ts
src/users/interfaces/user-data.interface.ts
test/bank-statements/bank-statements.e2e-spec.ts
test/utils/config.ts
test/utils/constants.ts

- feat: As catracadas agrupadas mostram o valor de cada tipo de pagamento
- fix: Correção na consistência dos dados, seguindo a tabela de testes unitários e de integração
- fix: seed de usuários padrão com senha  = `secret`

Corrigir dados financeiros  e seed de usuário

---

src/database/seeds/mail-history/mail-history-seed-data.service.ts
src/database/seeds/user/user-seed-data.service.ts
src/database/seeds/user/user-seed.service.ts
src/users/interfaces/user-data.interface.ts

- O identificador do seed será o email.
- A senha e id só serão sobrescritos na inserção se for a 1a vez que o usuário é populado no banco.
- Os itens do seed podem sobreescrever apenas a si próprios, baseado no email único.
- Todos os usuários populados no banco terão status de email = USADO.
- A senha dos usuários são 10 caracteres alfanuméricos aleatórios para cada usuário, gerado na hora e impresso no console do servidor.
- Se a senha do usuário no seed for 'secret' ele reseta a senha, sempre.
#102

feature: Popular usuários administradores

---

src/users/entities/user.entity.ts
src/users/users.module.ts
src/users/users.service.ts

- 🐞 fix: Não validar nome no upload de usuário
- 🐞 fix: Mostrar dados de banco com usuário

hotfix: Mostrar dados de banco, corrigir validação no upload

---

src/users/interfaces/find-user-paginated.interface.ts
src/users/users.controller.spec.ts
src/users/users.controller.ts
src/users/users.service.ts

hotfix: Ocultar admins no endpoint GET: users

---

src/auth/auth.service.spec.ts
src/auth/auth.service.ts
src/mail/mail-templates/report.hbs

- feat: formatar email de relatório
- feat: remover restrição, permitindo reenvio de email

Fetature: Corrigir email de relatório e reenvio de email

---

src/bank-statements/bank-statements-repository.service.ts
src/bank-statements/bank-statements.service.spec.ts
src/ticket-revenues/interfaces/tr-get-me-individual-args.interface.ts
src/ticket-revenues/ticket-revenues-repository.service.ts
src/ticket-revenues/ticket-revenues.module.ts
src/ticket-revenues/ticket-revenues.service.spec.ts
src/ticket-revenues/ticket-revenues.service.ts

- chore: Repositório ticket-revenues
- chore: Anotar métodos que precisam ser refatorados futuramente

Hotfix/#177 Endpoint transações individuais

---

src/auth-google/auth-google.service.ts
src/auth-licensee/auth-licensee.controller.ts
src/auth-licensee/auth-licensee.service.ts
src/auth-licensee/dto/auth-licensee-login.dto.ts
src/auth/auth.service.ts
src/bank-statements/bank-statements.service.spec.ts
src/config/app.config.ts
src/database/seeds/setting/setting-seed.service.ts
src/mail-history/mail-history.service.ts
src/mail-history/pipes/mail-history-validation.pipe.ts
src/settings/app.settings.ts
src/settings/entities/setting.entity.ts
src/settings/enums/bigquery-env.enum.ts
src/settings/settings.controller.ts
src/settings/settings.service.ts
src/ticket-revenues/ticket-revenues-repository.service.ts
src/ticket-revenues/ticket-revenues.module.ts
src/ticket-revenues/ticket-revenues.service.spec.ts
src/users/users.service.ts
src/utils/enums/http-error-message.enum.ts
src/utils/http-exception/common-http-exception.ts
src/utils/http-exception/http-exception-utils.ts
src/utils/validators/base-validator.ts
test/ticket-revenues/ticket-revenues.e2e-spec.ts

- fix: Usar tabela settings para escolher qual ambiente bigquery usar
- fix: Endpoint settings agora exige autenticação

Hotfix: Permitir variável de ambiente homol

---

src/auth/auth.controller.ts
src/bank-statements/bank-statements.service.spec.ts
src/bank-statements/bank-statements.service.ts
src/database/seeds/role/role-seed.service.ts
src/database/seeds/user/user-seed.service.ts

fix: merge to main, filter by start-end dates in bs

---

src/bigquery/dtos/bigquery-ordem-pagamento.dto.ts
src/bigquery/services/bigquery-ordem-pagamento.service.ts
src/cnab/service/transacao.service.ts

feat: validate bigqueryOrdemPgto

---

.eslintrc.js
package.json
src/cron-jobs/cron-jobs.service.ts
src/jae/data/jae-data.service.ts
src/mail-history/entities/mail-history.entity.ts
src/mail-history/mail-history.service.ts
src/users/users.service.ts

- feat: Reenviar emails para usuários2x por dia: 11:45 e 17:45, sem esperar 15 dias após o primeiro envio
- build: eslint ignora pasta de desenvolvimento local `local_dev`

feat: send cronjobs 2x a day

---

package.json
src/auth/auth.service.ts
src/core-bank/data/core-bank-data.service.ts
src/cron-jobs/cron-jobs.service.ts
src/database/seeds/mail-history/mail-history-seed-data.service.ts
src/jae/data/jae-data.service.ts
src/mail-history/mail-history.service.ts
src/mail/mail.service.ts
src/settings/settings.service.ts
src/users/users.service.ts
src/utils/all-exteptions-filter/filters/all-exceptions.filter.ts
src/utils/log-utils.ts

- fix: log-utils log message instead of object

fix: resend mails 1x per 30 days

---

src/auth-licensee/auth-licensee.service.ts

Todo o método **concludeRegistration** estará alinhado com os últimos requisitos: sem puxar de dados simulados.

fix: conclude registration with updated requirements

---

src/cron-jobs/cron-jobs.service.ts

- Mudança de requisito: job do retorno é a cada 2h

feat: job retorno each 2h

---

src/bank-statements/bank-statements.service.ts
src/bigquery/services/bigquery-transacao.service.ts
src/cnab/cnab.service.ts
src/cnab/service/arquivo-publicacao.service.ts
src/cron-jobs/cron-jobs.service.ts
src/database/seeds/test/cnab/cnab-update-transacao-view-bq/cnab-update-transacao-view-bq-seed-data.ts
src/database/seeds/test/cnab/cnab-update-transacao-view-bq/cnab-update-transacao-view-bq-seed.module.ts
src/database/seeds/test/cnab/cnab-update-transacao-view-bq/cnab-update-transacao-view-bq-seed.service.ts
src/home/git-info.class.ts
src/home/home.controller.ts
src/home/home.service.ts
src/ticket-revenues/ticket-revenues-repository.ts

- test: Integracao D+1
- test: (wip) Transacao x Publicacao
- feat: version and git info in /about
- refactor: comment unused methods

(main) fix: toPay values in bank-statements/me

---

src/cnab/cnab.controller.ts
src/cnab/cnab.service.ts
src/cnab/entity/arquivo-publicacao.entity.ts
src/cnab/entity/pagamento/detalhe-a.entity.ts
src/cnab/entity/pagamento/header-arquivo.entity.ts
src/cnab/entity/pagamento/header-lote.entity.ts
src/cnab/entity/pagamento/item-transacao-agrupado.entity.ts
src/cnab/entity/pagamento/item-transacao.entity.ts
src/cnab/entity/pagamento/transacao-agrupado.entity.ts
src/cnab/entity/pagamento/transacao-status.entity.ts
src/cnab/repository/arquivo-publicacao.repository.ts
src/cnab/repository/cliente-favorecido.repository.ts
src/cnab/repository/pagamento/detalhe-a.repository.ts
src/cnab/service/arquivo-publicacao.service.ts
src/cnab/service/cliente-favorecido.service.ts
src/cnab/service/ocorrencia.service.ts
src/cnab/service/pagamento/detalhe-a.service.ts
src/cnab/service/pagamento/remessa-retorno.service.ts
src/cnab/utils/cnab/cnab-utils.ts
src/database/data-source.ts
src/database/typeorm-config.service.ts
src/sftp/sftp.service.ts
src/utils/custom-logger.ts

- chore: env to show typeorm and debug logging
- perf: faster query - 5-10 min -> 0.5s
- fix: read last line with Registros A,B or A,B,Z
- fix: move retorno from origin folder instead of default location

(prod) Fix/388-sincronismo-retorno

---

src/auth-licensee/auth-licensee.service.ts
src/auth/auth.controller.ts
src/auth/auth.service.ts
src/bigquery/bigquery.service.ts
src/bigquery/repositories/bigquery-ordem-pagamento.repository.ts
src/bigquery/repositories/bigquery-transacao.repository.ts
src/bigquery/services/bigquery-ordem-pagamento.service.ts
src/bigquery/services/bigquery-transacao.service.ts
src/cnab/cnab.service.ts
src/cnab/repository/arquivo-publicacao.repository.ts
src/cnab/repository/cliente-favorecido.repository.ts
src/cnab/repository/extrato/extrato-detalhe-e.repository.ts
src/cnab/repository/ocorrencia.repository.ts
src/cnab/repository/pagamento/detalhe-a.repository.ts
src/cnab/service/pagamento/detalhe-a.service.ts
src/cnab/service/pagamento/remessa-retorno.service.ts
src/users/users.service.ts
src/utils/custom-logger.ts

- refactor: CustomLogger instead of logger
- fix: log error message of nested HttpException

(prod) fix: If detalheA not found, move to failed

---

src/cnab/service/pagamento/detalhe-a.service.ts
src/cnab/service/pagamento/remessa-retorno.service.ts
src/cron-jobs/cron-jobs.service.ts
src/settings/settings.service.ts
src/sftp/sftp-client/sftp-client.service.ts
src/sftp/sftp.service.ts

- fix: sftp rename if origin/dest is the same

(prod) fix: try-catch for cronjobs

---

src/cnab/cnab.service.ts
src/cnab/dto/pagamento/header-lote.dto.ts
src/cnab/service/pagamento/remessa-retorno.service.ts
src/cnab/utils/cnab/cnab-field-utils.ts

- wip: Comentar método de buscar Lançamento (falta corrigit bug na busca e join)
- fix: codCompromisso não era adicionado no remessa
- fix: nome do cnab remessa salvava no banco com diretório.

Comentar Lançamento no remessa e correções

---

src/cnab/repository/cliente-favorecido.repository.ts
src/cnab/repository/pagamento/detalhe-a.repository.ts
src/cnab/service/pagamento/detalhe-a.service.ts

Agora é usado nome, valor efetivado e data de efetivação como identificação para att do detalhe A

feat:  Nova Lógica de leitura retorno

---

src/cnab/repository/cliente-favorecido.repository.ts
src/cnab/repository/pagamento/detalhe-a.repository.ts
src/cnab/service/pagamento/detalhe-a.service.ts

Leitura usando o valor lançamento e num. doc. Empresa como param, para conseguir ler consórcios

fix: ler retornos consórcios

---

src/relatorio/dtos/relatorio-consolidado-novo-remessa.dto.ts
src/relatorio/interfaces/find-publicacao-relatorio-novo-remessa.interface.ts
src/relatorio/relatorio-novo-remessa.controller.ts
src/relatorio/relatorio-novo-remessa.repository.ts
src/relatorio/relatorio-novo-remessa.service.ts
src/relatorio/relatorio.module.ts

Nova implementação do relatório consolidado

Relatório Consolidado

---

src/cnab/novo-remessa/service/ordem-pagamento-agrupado.service.ts
src/cron-jobs/cron-jobs.service.ts

adiciona uns logs pra saber o motivo de nao agrupar.
agrupa e sincroniza no startup

modifica a aplicacao para obter as ordens

---

src/relatorio/relatorio-novo-remessa.repository.ts

Corrige a query dos relatorios

fix report

---

src/cron-jobs/cron-jobs.service.ts

Revert "teste nova variavel ambiente"

---

.kubernetes/dev/k8s.yaml
.kubernetes/prod/k8s.yaml

Adiciona termos de nodeAffinity aos pods da cct para que rodem  em uma nodePool separada dos demais recursos do cluster

[Feature] Adiciona nodeAffinity  aos pods

---

src/relatorio/dtos/detalhado-query.dto.ts
src/relatorio/interfaces/filter-publicacao-relatorio-novo-detalhado.interface.ts
src/relatorio/relatorio-novo-remessa-detalhado.repository.ts
src/relatorio/relatorio-novo-remessa-detalhado.service.ts

Fix Filters and query for 2024
